### ISSUE TITLE
Precisam de ajuda?

### ISSUE THREAD

**Issue by FBrauns** [GuilhermeTel/Site-Uniriotec-EJ#1]
Então, qualquer coisa necessária podem falar comigo. eu to disponivel pra ajudar nos requisitos e até em mentoria sobre funcionamento e tecnologia.

**Comment by GuilhermeTel** [comment]
Ajuda sempre é bem vinda! 
Villaça nos deu algumas dicas sobre divisão de tarefas e detalhamento do escopo inicial, mas o que acho que precisamos precisa saber também é até onde vai a liberdade de criação dentro do projeto, me refiro a questões sobre layout, padrão de cores e etc.

**Comment by villaca** [comment]
Padrão de cores por enquanto vcs podem manter as cores das logos, talvez variações próximas e cores leves.

Se quiserem brincar com cores: https://color.adobe.com/pt/create/color-wheel/

**Comment by villaca** [comment]
Layout eu não tenho ideia pra sugerir, podem consultar a Vanessa se ela tem algo em mente.
